### PR TITLE
update to the latest PlantUML version.

### PR DESCRIPTION
**Pull request by aadrian**

### CODE REVIEW

**Comment by aadrian** [comment]
any news merging this PR?

**Comment by nus** [comment]
@aadrian 

Thank you for your PR!

I compared plantuml.jar in the commit with https://sourceforge.net/projects/plantuml/files/1.2017.16/plantuml-jar-asl-1.2017.16.zip/download .

The following is MD5 hash of plantuml in the commit.

```
MD5 of plantuml.jar in the commit.
> certutil.exe -hashfile .\plantuml.jar MD5
...
b354c676b224d3e62ac5e55d34a85f90
```
But https://sourceforge.net/projects/plantuml/files/1.2017.16/plantuml-jar-asl-1.2017.16.zip/download is as follows.

```
> certutil.exe -hashfile .\plantuml.jar MD5
...
7e4fd91e8aff22c19d6d9469e4838234
```

Could you tell me  URL of plantuml.jar which you downloaded.

**Comment by aadrian** [comment]
> Could you tell me URL of plantuml.jar which you downloaded.

It's from the official site, whatever the official files might be now, since nobody really knows https://github.com/plantuml/plantuml/releases (this version is not even tagged).

The author refuses to use something that is easy to track or to distribute all artifacts in a Maven repo, even when proposed to modularize the project https://github.com/plantuml/plantuml/wiki/Module-Proposal  so that only the 'extra' code as a module to be non-ASL licensed. 

As you can also see https://github.com/plantuml/plantuml/pulls PRs were not included as PRs but copied by hand, and there are no "commits" , but just complete "backups" there.

Considering this chaos there, I really don't care about a Hash, since we don't really know what we are hashing.

**Comment by aadrian** [comment]
Since PlantUML can now is downloaded at build time, this PR is obsolete.

**Pull request closed without merging**
