### PR TITLE
update plantuml.jar to version "8059"

### PR DESCRIPTION
**Pull request by aadrian**
see #4

### CODE REVIEW

**Comment by nus** [comment]
What is the license of the jar file?

**Comment by aadrian** [comment]
> What is the license of the jar file?

@nus It's the official JAR available from the official website.

Also now it's "obsolete", since there's a newer version since I made this PR that does some fixes: V8059 http://plantuml.com/changes

**Comment by nus** [comment]
> It's the official JAR available from the official website.

OK, the jar file may be GPL.
If possible, could you change to Apache Software License Version?

https://sourceforge.net/projects/plantuml/files/plantuml-jar-asl-8058.zip/download

**Comment by aadrian** [comment]
@nus 

> If possible, could you change to Apache Software License Version?

Just did, and also updated to 8059.

**Comment by nus** [comment]
@aadrian Thank you!

**Pull request merged**
